# -*-encoding:utf-8 -*-

value_dict = \
    {'水泥A-1-上海水泥网': {'column': '产业动态',
  'origin_deptment': '上海水泥行业协会',
  'origin_place': '上海',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-2-海螺物资阳光采购平台': {'column': '招标买卖',
  'origin_deptment': '海螺物资阳光采购平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-3-中原招采网': {'column': '招标买卖',
  'origin_deptment': '中原招采网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-4-宁夏建材采购管理平台': {'column': '招标买卖',
  'origin_deptment': '宁夏建材采购管理平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-5-1688大企业采购': {'column': '招标买卖',
  'origin_deptment': '1688大企业采购',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-6-金隅冀东阳光采购平台': {'column': '招标买卖',
  'origin_deptment': '金隅冀东阳光采购平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-7-红狮招标公告': {'column': '招标买卖',
  'origin_deptment': '红狮招标公告',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-8-华润水泥': {'column': '招标买卖',
  'origin_deptment': '华润水泥网上招采平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-9-祁连山电子采购平台': {'column': '招标买卖',
  'origin_deptment': '祁连山电子采购平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-10-祁连山电子采购平台': {'column': '招标买卖',
  'origin_deptment': '祁连山电子采购平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-11-华新招选平台': {'column': '招标买卖',
  'origin_deptment': '华新水泥招选平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-12-华新招选平台': {'column': '招标买卖',
  'origin_deptment': '华新水泥招选平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '水泥A-13-金隅冀东阳光采购平台': {'column': '招标买卖',
  'origin_deptment': '金隅冀东阳光采购平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水泥'},
 '建材A-25-中华建材网': {'column': '产业动态',
  'origin_deptment': '中华建材网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '建材'},
 '建材A-26-中华建材网': {'column': '产业动态',
  'origin_deptment': '中华建材网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '建材'},
 '公路桥梁A-19-中国路面机械网': {'column': '产业动态',
  'origin_deptment': '中国路面机械网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '公路桥梁'},
 '公路桥梁A-20-中国路面机械网': {'column': '产业动态',
  'origin_deptment': '中国路面机械网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '公路桥梁'},
 '轨道交通A-2-中国城市轨道交通协会': {'column': '产业动态',
  'origin_deptment': '中国城市轨道交通协会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-4-中国城市轨道交通协会': {'column': '产业动态',
  'origin_deptment': '中国城市轨道交通协会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-36-轨道招标网': {'column': '招标买卖',
  'origin_deptment': '轨道招标网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-37-轨道招标网': {'column': '招标买卖',
  'origin_deptment': '轨道招标网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-38-轨道招标网': {'column': '招标买卖',
  'origin_deptment': '轨道招标网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-57-上海地铁采购电子商务平台': {'column': '招标买卖',
  'origin_deptment': '上海地铁采购电子商务平台',
  'origin_place': '上海',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '轨道交通A-71-广州地铁': {'column': '招标买卖',
  'origin_deptment': '广州地铁招投标网站',
  'origin_place': '广州',
  'origin_type': '产业网站',
  'industry_class': '轨道交通'},
 '建筑建设A-85-ABBS建筑论坛': {'column': '产业动态',
  'origin_deptment': 'ABBS建筑论坛',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '建筑建设'},
 '建筑建设A-89-中国城镇供排水协会': {'column': '产业动态',
  'origin_deptment': '中国城镇供排水协会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '建筑建设'},
 '建筑建设A-189-建筑网': {'column': '技术标准',
  'origin_deptment': '建筑网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '建筑建设'},
 '铁路建设A-19-高铁网': {'column': '产业动态',
  'origin_deptment': '高铁网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '铁路建设'},
 '铁路建设A-34-中国铁路工程建设网': {'column': '产业动态',
  'origin_deptment': '中国铁路工程建设网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '铁路建设'},
 '铁路建设A-77-中铁鲁班商务网': {'column': '招标买卖',
  'origin_deptment': '中铁鲁班商务网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '铁路建设'},
 '铁路建设A-78-中铁鲁班商务网': {'column': '招标买卖',
  'origin_deptment': '中铁鲁班商务网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '铁路建设'},
 '水利工程A-26-中国水利': {'column': '产业动态',
  'origin_deptment': '中国水利网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '水利工程'},
 '能源A-11-中国能源网': {'column': '产业动态',
  'origin_deptment': '中国能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-12-中国能源网': {'column': '行业动态',
  'origin_deptment': '中国能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-15-中国能源网': {'column': '行业动态',
  'origin_deptment': '中国能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-17-中国能源网': {'column': '行业动态',
  'origin_deptment': '中国能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-58-中国能建': {'column': '行业动态',
  'origin_deptment': '全球能源信息平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-59-中国储能网': {'column': '行业动态',
  'origin_deptment': '中国储能网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-60-中国储能网': {'column': '行业动态',
  'origin_deptment': '中国储能网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-62-中国储能网': {'column': '行业动态',
  'origin_deptment': '中国储能网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-125-国际太阳能光伏网': {'column': '行业动态',
  'origin_deptment': '国际能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-128-国际太阳能光伏网': {'column': '行业动态',
  'origin_deptment': '国际能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-142-国际新能源网': {'column': '行业动态',
  'origin_deptment': '国际新能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-149-国际石油网': {'column': '行业动态',
  'origin_deptment': '国际石油网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-199-全球新能源网': {'column': '行业动态',
  'origin_deptment': '全球新能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-201-全球新能源网': {'column': '行业动态',
  'origin_deptment': '全球新能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-206-全球新能源网': {'column': '行业动态',
  'origin_deptment': '全球新能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '能源A-262-国际新能源网': {'column': '市场行情',
  'origin_deptment': '国际新能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '煤炭A-2-中国煤机网': {'column': '行业动态',
  'origin_deptment': '中国煤机网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '煤炭'},
 '煤炭A-9-我的煤炭网': {'column': '行业动态',
  'origin_deptment': '我的煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '煤炭'},
 '煤炭A-10-我的煤炭网': {'column': '行业动态',
  'origin_deptment': '我的煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '煤炭'},
 '煤炭A-11-我的煤炭网': {'column': '行业动态',
  'origin_deptment': '我的煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '煤炭'},
 '煤炭A-12-我的煤炭网': {'column': '行业动态',
  'origin_deptment': '我的煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '煤炭'},
 '煤炭A-44-5e中国能源网': {'column': '行业动态',
  'origin_deptment': '中国能源网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '煤炭A-70-我的煤炭网': {'column': '市场行情',
  'origin_deptment': '我的煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '能源'},
 '机械A-15-中国机械社区': {'column': '产业动态',
  'origin_deptment': '中国机械社区',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '机械'},
 '机械A-16-中国机械社区': {'column': '产业动态',
  'origin_deptment': '中国机械社区',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '机械'},
 '机械A-26-四川省装备制造技术服务平台': {'column': '产业动态',
  'origin_deptment': '四川省装备制造技术服务平台',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '机械'},
 '机电A-12-中国机电产品出口商会': {'column': '产业动态',
  'origin_deptment': '中国机电产品出口商会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '机电'},
 '机械A-12-工程机械新闻': {'column': '产业动态',
  'origin_deptment': '工程机械新闻',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '工程机械'},
 '机械A-23-工程机械在线': {'column': '产业动态',
  'origin_deptment': '工程机械在线',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '工程机械'},
 '机械仪器仪表A-10-中国分析测试协会': {'column': '产业动态',
  'origin_deptment': '中国分析测试协会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '仪器仪表'},
 '机械仪器仪表A-46-维库仪器仪表网': {'column': '产业动态',
  'origin_deptment': '维库仪器仪表网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '仪器仪表'},
 '机械仪器仪表A-51-仪器网': {'column': '产业动态',
  'origin_deptment': '仪器网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '仪器仪表'},
 '房地产A-44-合肥市房地产协会': {'column': '产业动态',
  'origin_deptment': '合肥市房地产协会',
  'origin_place': '合肥市',
  'origin_type': '产业网站',
  'industry_class': '房地产'},
 '房地产A-56-房天下': {'column': '产业动态',
  'origin_deptment': '房天下产业网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '房地产'},
 '钢铁A-5-冶金工业网': {'column': '产业动态',
  'origin_deptment': '冶金工业网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '钢铁A-6-中国冶金科工集团': {'column': '产业动态',
  'origin_deptment': '中国中冶科工集团',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '钢铁A-19-中钢网': {'column': '产业动态',
  'origin_deptment': '中钢网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '钢铁A-22-钢材价格网': {'column': '产业动态',
  'origin_deptment': '钢材价格网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '钢铁A-26-煤炭网': {'column': '产业动态',
  'origin_deptment': '煤炭网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '钢铁A-36-兰格钢铁网': {'column': '产业动态',
  'origin_deptment': '兰格钢铁网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '钢铁'},
 '矿业A-25-矿业交易网': {'column': '产业动态',
  'origin_deptment': '矿业交易网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '矿业'},
 '矿业A-55-矿业交易网': {'column': '产业动态',
  'origin_deptment': '矿业交易网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '矿业'},
 '矿业A-30-中国矿业网': {'column': '产业动态',
  'origin_deptment': '中国矿业联合会中国矿业网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '矿业'},
 '矿业A-31-中国矿业网': {'column': '产业动态',
  'origin_deptment': '中国矿业联合会中国矿业网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '矿业'},
 '环保产业A-33-第一环保网': {'column': '产业动态',
  'origin_deptment': '第一环保网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '环保产业'},
 '环保产业A-86-国际节能环保网': {'column': '产业动态',
  'origin_deptment': '国际节能环保网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '环保产业'},
 '环保产业A-92-国际节能环保网': {'column': '产业动态',
  'origin_deptment': '国际节能环保网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '环保产业'},
 '环保产业A-93-国际节能环保网': {'column': '产业动态',
  'origin_deptment': '国际节能环保网',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': '环保产业'},
 '公共资源交易A-1-四川省': {'column': '招标买卖',
  'origin_deptment': '四川省公共资源交易网',
  'origin_place': '四川省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-2-云南省': {'column': '招标买卖',
  'origin_deptment': '云南省公共资源交易网',
  'origin_place': '云南省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-3-北京市': {'column': '招标买卖',
  'origin_deptment': '北京公共资源交易中心',
  'origin_place': '北京市',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-7-江苏省': {'column': '招标买卖',
  'origin_deptment': '江苏省公共资源交易网',
  'origin_place': '江苏省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-17-甘肃省': {'column': '招标买卖',
  'origin_deptment': '甘肃省公共资源交易局',
  'origin_place': '甘肃省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-18-宁夏': {'column': '招标买卖',
  'origin_deptment': '宁夏公共资源交易网',
  'origin_place': '宁夏',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-21-辽宁省': {'column': '招标买卖',
  'origin_deptment': '沈阳市公共资源交易平台',
  'origin_place': '沈阳市',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-33-北京市': {'column': '招标买卖',
  'origin_deptment': '北京市公共资源交易平台',
  'origin_place': '北京市',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-34-北京市': {'column': '招标买卖',
  'origin_deptment': '北京市公共资源交易平台',
  'origin_place': '北京市',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-39-山西省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（山西）',
  'origin_place': '山西省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-40-山西省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（山西）',
  'origin_place': '山西省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-50-湖南省': {'column': '招标买卖',
  'origin_deptment': '湖南省公共资源交易平台',
  'origin_place': '湖南省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-97-海南省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（海南省）',
  'origin_place': '海南省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-100-陕西省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（陕西省）',
  'origin_place': '陕西省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-103-陕西省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（陕西省）',
  'origin_place': '陕西省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-106-黑龙江省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（黑龙江省）',
  'origin_place': '黑龙江省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-144-福建省': {'column': '招标买卖',
  'origin_deptment': '福建省公共资源交易电子公共服务平台',
  'origin_place': '福建省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-145-福建省': {'column': '招标买卖',
  'origin_deptment': '福建省公共资源交易电子公共服务平台',
  'origin_place': '福建省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-147-福建省': {'column': '招标买卖',
  'origin_deptment': '福建省公共资源交易电子公共服务平台',
  'origin_place': '福建省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-159-内蒙古': {'column': '招标买卖',
  'origin_deptment': '内蒙古公共资源交易网',
  'origin_place': '内蒙古',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-161-内蒙古': {'column': '招标买卖',
  'origin_deptment': '内蒙古公共资源交易网',
  'origin_place': '内蒙古',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-165-江西省': {'column': '招标买卖',
  'origin_deptment': '江西省公共资源交易中心',
  'origin_place': '江西省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '公共资源交易A-188-河南省': {'column': '招标买卖',
  'origin_deptment': '全国公共资源交易平台（河南省）',
  'origin_place': '河南省',
  'origin_type': '政府部门',
  'industry_class': ''},
 '国家级URL-49-钢构之窗A': {'column': '宏观经济',
  'origin_deptment': '钢构之窗',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': ''},
 '国家级URL-50-中国铁合金在线A': {'column': '宏观经济',
  'origin_deptment': '中国铁合金在线',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': ''},
 '国家级URL-59-中国招投标协会A ': {'column': '宏观经济',
  'origin_deptment': '中国招投标协会',
  'origin_place': '中国',
  'origin_type': '产业网站',
  'industry_class': ''},
 '国家级URL-67-吉林省经济信息网A': {'column': '政府动态',
  'origin_deptment': '吉林省经济信息网',
  'origin_place': '吉林',
  'origin_type': '政府部门',
  'industry_class': ''},
 '国家级URL-109-中央人民政府A': {'column': '政府动态',
  'origin_deptment': '中国政府网',
  'origin_place': '中国',
  'origin_type': '政府部门',
  'industry_class': ''},
 '国家级URL-187-中央人民政府A': {'column': '政府动态',
  'origin_deptment': '中国政府网',
  'origin_place': '中国',
  'origin_type': '政府部门',
  'industry_class': ''}}